# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import latest657.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=50, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=latest657.models.unique_file_name)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=latest657.models.unique_file_name, validators=[latest657.models.validate_audio])),
                ('video_file', models.FileField(blank=True, null=True, upload_to=latest657.models.unique_file_name, validators=[latest657.models.validate_video])),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
