# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import latest657.models


class Migration(migrations.Migration):

    dependencies = [
        ('latest657', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=latest657.models.unique_file_name, validators=[latest657.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
