# Generated by Django 2.2.1 on 2019-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest657', '0002_auto_20190316_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_color',
            field=models.CharField(blank=True, default='#0000', max_length=50, null=True),
        ),
    ]
