# Generated by Django 2.2.1 on 2019-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest657', '0004_post_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_opacity',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
    ]
